# change the followings to match your Github username and repo name
baseurl: "/tailpages" # the name of your github repo
url: "https://pasamonteg.github.io/" # the url of your github pages

# site information used in page title, meta data etc.
title: "Tailpages: Tailwind + Github Pages"
description: A Github Pages (Jekyll) template based on TailwindCSS

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Ginés de Pasamonte
author-bio: Professional Malote  # change to false to hide
author-image: gines.jpg  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: Bitcoin
  permalink: bitcoin
- text: Blog
  permalink: blog

# use false to turn off any social media links
twitter: false #https://twitter.com/
facebook: false #https://facebook.com/
instagram: false #https://instagram.com/
github: https://github.com/
linkedin: false #https://linkedin.com/
medium: false #false
google-scholar: false #false
email: false #false

# footer information
footer-msg: "Powered by Tailpages"
footer-msg-link: https://pasamonteg.github.io/tailpages

# google analytics
google-analytics: false #G-WCRC1TC2V5

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
